[Issue #1548] sprint reports step function (#1604)
## Summary
Fixes https://github.com/HHS/simpler-grants-gov/issues/1548

### Time to review: __5 mins__

## Code writing process

- renamed `copy_oracle_data.tf`
- copied `sfn_copy_oracle_data.tf` to `sfn_sprint_reports.tf`, renamed
_"copy oracle data"_ inside of that file to _"sprint report"_
- updated the `Command`
https://github.com/HHS/simpler-grants-gov/blob/4ee41df84d7a4504494b755ff900edcd41918e8b/infra/analytics/service/sfn_sprint_reports.tf#L28-L32
- added `aws_cloudwatch_log_group` to fix an error:

> Error: creating Step Functions State Machine
(analytics-dev-sprint-reports): InvalidLoggingConfiguration: Invalid
Logging Configuration: The CloudWatch Logs Resource Policy size was
exceeded. We suggest prefixing your CloudWatch log group name with
/aws/vendedlogs/states/.

## Changes proposed

Adds a sprint reporting data step function

## Testing

<img width="737" alt="image"
src="https://github.com/HHS/simpler-grants-gov/assets/5768468/c5dcbad5-bd3b-42d0-a6b6-2d602d5c8d4f">

Not working yet due to
https://github.com/HHS/simpler-grants-gov/issues/837